SD JWT javascript 2024 Annual Review
openwallet-foundation/tac pull request #196
Opened 2024-11-27 02:05 UTC by lukasjhan

Hi TAC members.

I wrote the brief information of the annual review.

Thank you.

2024-12-02 16:25 UTC, tkuhrt requested changes
Minor changes requested. Looks good otherwise.

2024-12-02 16:25 UTC, tkuhrt commented on docs/projects/reviews/2024/2024-sd-jwt-js-annual.md
> +# YYYY PROJECT NAME
```suggestion
# 2024 SD-JWT JavaScript Annual Review
```

2024-12-02 16:25 UTC, tkuhrt commented on docs/projects/reviews/2024/2024-sd-jwt-js-annual.md
> +- Brend ([Github](https://github.com/berendsliedrecht))
This list does not seem to match the code owners file.

2024-12-04 12:18 UTC, TimoGlastra commented on docs/projects/reviews/2024/2024-sd-jwt-js-annual.md
> +- Brend ([Github](https://github.com/berendsliedrecht))
```suggestion
- Berend Sliedrecht ([Github](https://github.com/berendsliedrecht))
```

2024-12-04 12:32 UTC, lukasjhan commented on docs/projects/reviews/2024/2024-sd-jwt-js-annual.md
> +- Brend ([Github](https://github.com/berendsliedrecht))
Thank you

2024-12-04 14:52 UTC, tkuhrt commented on docs/projects/reviews/2024/2024-sd-jwt-js-annual.md
> +- Berend Sliedrecht ([Github](https://github.com/berendsliedrecht))
```suggestion
- Berend Sliedrecht ([Github](https://github.com/berendsliedrecht))
- Mirko Mollik ([Github](https://github.com/cre8))
```

2024-12-10 00:25 UTC, tkuhrt approved these changes

2024-12-10 19:41 UTC, swcurran approved these changes

2024-12-11 06:11 UTC, skounis approved these changes

2024-12-11 20:21 UTC, tkuhrt commented
Unanimously approved at the December 11, 2024 meeting

2024-12-11 20:21 UTC, merged